import type { Theme } from "../../theme/contract";

export type CatppuccinPalette = {
  rosewater: string;
  flamingo: string;
  pink: string;
  mauve: string;
  red: string;
  maroon: string;
  peach: string;
  yellow: string;
  green: string;
  teal: string;
  sky: string;
  sapphire: string;
  blue: string;
  lavender: string;
  text: string;
  subtext1: string;
  subtext0: string;
  overlay2: string;
  overlay1: string;
  overlay0: string;
  surface2: string;
  surface1: string;
  surface0: string;
  base: string;
  mantle: string;
  crust: string;
};

const withAlpha = (color: string, alpha: number): string =>
  color.replace("rgb(", "rgba(").replace(")", `, ${alpha})`);

export function compileCatppuccinTheme(
  id: string,
  name: string,
  palette: CatppuccinPalette,
): Theme {
  const {
    rosewater,
    flamingo,
    pink,
    mauve,
    red,
    maroon,
    peach,
    yellow,
    green,
    sky,
    blue,
    lavender,
    text,
    subtext1,
    overlay2,
    overlay1,
    overlay0,
    surface2,
    surface1,
    surface0,
    base,
    mantle,
    crust,
  } = palette;

  return {
    id,
    name,
    variables: {
      "--color-border-brand": mauve,
      "--color-border-discreet": surface2,
      "--color-border-discreet-a": surface2,
      "--color-border-error": red,
      "--color-border-info": sky,
      "--color-border-main": surface2,
      "--color-border-subtle": surface2,
      "--color-border-success": green,
      "--color-border-warning": peach,
      "--color-button-buy-hover": blue,
      "--color-button-buy-normal": blue,
      "--color-button-buy-normal-text": base,
      "--color-button-buy-pressing": blue,
      "--color-button-discreet-border": overlay1,
      "--color-button-discreet-emphasize": mauve,
      "--color-button-discreet-hover": surface1,
      "--color-button-discreet-hover-text": text,
      "--color-button-discreet-normal": base,
      "--color-button-discreet-normal-text": text,
      "--color-button-discreet-pressing": surface1,
      "--color-button-discreet-pressing-text": text,
      "--color-button-minimal-buy-hover": blue,
      "--color-button-minimal-buy-hover-text": base,
      "--color-button-minimal-buy-normal": "transparent",
      "--color-button-minimal-buy-normal-text": blue,
      "--color-button-minimal-buy-pressing": blue,
      "--color-button-minimal-buy-pressing-text": base,
      "--color-button-minimal-discreet-hover-text": text,
      "--color-button-minimal-discreet-normal": "transparent",
      "--color-button-minimal-discreet-normal-text": text,
      "--color-button-minimal-discreet-pressing-text": text,
      "--color-button-minimal-handle": text,
      "--color-button-minimal-primary-hover-text": mauve,
      "--color-button-minimal-primary-normal": "transparent",
      "--color-button-minimal-primary-normal-text": mauve,
      "--color-button-minimal-primary-pressing-text": mauve,
      "--color-button-minimal-secondary-hover-text": text,
      "--color-button-minimal-secondary-normal": "transparent",
      "--color-button-minimal-secondary-normal-text": text,
      "--color-button-minimal-secondary-pressing-text": text,
      "--color-button-minimal-sell-hover": red,
      "--color-button-minimal-sell-hover-text": red,
      "--color-button-minimal-sell-normal": "transparent",
      "--color-button-minimal-sell-normal-text": red,
      "--color-button-minimal-sell-pressing": red,
      "--color-button-minimal-sell-pressing-text": red,
      "--color-button-minimal-warning-hover-text": peach,
      "--color-button-minimal-warning-normal": "transparent",
      "--color-button-minimal-warning-normal-text": peach,
      "--color-button-minimal-warning-pressing-text": peach,
      "--color-button-non-essential-normal-text": overlay0,
      "--color-button-primary-hover": mauve,
      "--color-button-primary-normal": mauve,
      "--color-button-primary-normal-text": base,
      "--color-button-primary-pressing": mauve,
      "--color-button-secondary-border": overlay1,
      "--color-button-secondary-hover": surface1,
      "--color-button-secondary-hover-text": text,
      "--color-button-secondary-normal": base,
      "--color-button-secondary-normal-text": text,
      "--color-button-secondary-pressing": surface1,
      "--color-button-secondary-pressing-text": text,
      "--color-button-sell-hover": red,
      "--color-button-sell-normal": red,
      "--color-button-sell-normal-text": base,
      "--color-button-sell-pressing": red,
      "--color-disabled-button-minimal-text": overlay0,
      "--color-disabled-discreet": surface1,
      "--color-disabled-discreet-border": overlay0,
      "--color-disabled-discreet-text": overlay0,
      "--color-disabled-feedback-icon": overlay0,
      "--color-disabled-group": surface1,
      "--color-disabled-group-border": overlay0,
      "--color-disabled-group-text": overlay0,
      "--color-disabled-input-checked": overlay0,
      "--color-disabled-input-placeholder-text": overlay0,
      "--color-disabled-normal": surface1,
      "--color-disabled-normal-border": overlay0,
      "--color-disabled-normal-text": overlay0,
      "--color-graph-area": withAlpha(mauve, 0.2),
      "--color-graph-discreet-stroke": surface2,
      "--color-graph-down": red,
      "--color-graph-gradient-start": withAlpha(mauve, 0.2),
      "--color-graph-horizontal-line": peach,
      "--color-graph-marketmaker-area": surface2,
      "--color-graph-primary-stroke": mauve,
      "--color-graph-series-column": surface2,
      "--color-graph-series-column-empty": surface2,
      "--color-graph-series-stroke-a": rosewater,
      "--color-graph-series-stroke-b": mauve,
      "--color-graph-series-stroke-c": peach,
      "--color-graph-series-stroke-d": sky,
      "--color-graph-series-stroke-e": blue,
      "--color-graph-series-stroke-f": pink,
      "--color-graph-series-stroke-g": red,
      "--color-graph-series-stroke-h": green,
      "--color-graph-series-stroke-i": lavender,
      "--color-graph-series-stroke-j": flamingo,
      "--color-graph-series-stroke-k": maroon,
      "--color-graph-surface-info": surface2,
      "--color-graph-up": green,
      "--color-icon-discreet": subtext1,
      "--color-icon-error": red,
      "--color-icon-feedback-happy": green,
      "--color-icon-feedback-semi-happy": green,
      "--color-icon-feedback-semi-unhappy": red,
      "--color-icon-feedback-unhappy": red,
      "--color-icon-info": sky,
      "--color-icon-morningstar-rating-emphasize": yellow,
      "--color-icon-morningstar-rating-inactive": yellow,
      "--color-icon-negative": red,
      "--color-icon-neutral": text,
      "--color-icon-non-essential": overlay0,
      "--color-icon-positive": green,
      "--color-icon-primary": mauve,
      "--color-icon-secondary": text,
      "--color-icon-success": green,
      "--color-icon-warning": peach,
      "--color-indicator-alert": red,
      "--color-indicator-buy": blue,
      "--color-indicator-discreet": text,
      "--color-indicator-incite": green,
      "--color-indicator-info": sky,
      "--color-indicator-primary": mauve,
      "--color-indicator-sell": red,
      "--color-input-border": overlay1,
      "--color-input-border-high-contrast": overlay1,
      "--color-input-borderless-normal": overlay1,
      "--color-input-borderless-normal-text": overlay1,
      "--color-input-borderless-placeholder-text": overlay1,
      "--color-input-checked": mauve,
      "--color-input-checked-content": base,
      "--color-input-emphasize": mauve,
      "--color-input-label-text": text,
      "--color-input-normal": base,
      "--color-input-normal-text": text,
      "--color-input-placeholder-text": overlay1,
      "--color-input-text-field-border-active": mauve,
      "--color-input-text-field-border-bottom": surface2,
      "--color-list-neutral-expanded": surface0,
      "--color-list-neutral-expanded-a": surface0,
      "--color-list-neutral-hover": surface1,
      "--color-list-neutral-pressing": surface1,
      "--color-list-neutral-selected": withAlpha(overlay2, 0.25),
      "--color-list-normal": base,
      "--color-persistent-black": crust,
      "--color-persistent-white": base,
      "--color-placera-border": surface2,
      "--color-placera-brand": mauve,
      "--color-placera-button-hover": surface1,
      "--color-placera-button-minimal-hover-text": text,
      "--color-placera-button-minimal-normal": "transparent",
      "--color-placera-button-minimal-normal-text": text,
      "--color-placera-button-minimal-pressing-text": text,
      "--color-placera-button-normal": mauve,
      "--color-placera-button-normal-text": base,
      "--color-placera-button-pressing": surface1,
      "--color-placera-surface-hover": surface1,
      "--color-placera-surface-main": base,
      "--color-placera-text-brand": mauve,
      "--color-placera-text-discreet": subtext1,
      "--color-placera-text-main": text,
      "--color-selectable-border": overlay1,
      "--color-selectable-border-high-contrast": overlay1,
      "--color-selectable-emphasize": mauve,
      "--color-selectable-hover": surface1,
      "--color-selectable-hover-text": text,
      "--color-selectable-inactive": mauve,
      "--color-selectable-normal": base,
      "--color-selectable-normal-text": text,
      "--color-selectable-pressing": surface1,
      "--color-selectable-pressing-text": text,
      "--color-selectable-selected": withAlpha(overlay2, 0.25),
      "--color-selectable-selected-text": text,
      "--color-shadow-card": withAlpha(text, 0.08),
      "--color-shadow-card-hover": withAlpha(text, 0.16),
      "--color-shadow-main": withAlpha(text, 0.08),
      "--color-shadow-overlay": withAlpha(text, 0.35),
      "--color-skeleton-loading-card": surface0,
      "--color-skeleton-loading-element": surface0,
      "--color-skeleton-loading-highlight-element": surface0,
      "--color-surface-backdrop": withAlpha(text, 0.35),
      "--color-surface-brand": surface0,
      "--color-surface-discreet": surface0,
      "--color-surface-discreet-a": surface0,
      "--color-surface-discreet-hover": surface1,
      "--color-surface-elevated": surface0,
      "--color-surface-elevated-primary": surface0,
      "--color-surface-elevated-secondary": surface0,
      "--color-surface-elevated-tertiary": surface0,
      "--color-surface-error": surface0,
      "--color-surface-error-a": surface0,
      "--color-surface-info": surface0,
      "--color-surface-info-a": surface0,
      "--color-surface-main": base,
      "--color-surface-negative": surface0,
      "--color-surface-neutral": surface0,
      "--color-surface-neutral-a": surface0,
      "--color-surface-offline": crust,
      "--color-surface-positive": surface0,
      "--color-surface-subtle": mantle,
      "--color-surface-success": surface0,
      "--color-surface-success-a": surface0,
      "--color-surface-transparent": withAlpha(base, 0.001),
      "--color-surface-warning": surface0,
      "--color-surface-warning-a": surface0,
      "--color-tag-hover": surface1,
      "--color-tag-negative-hover": red,
      "--color-tag-negative-normal": red,
      "--color-tag-negative-normal-text": base,
      "--color-tag-negative-pressing": red,
      "--color-tag-negative-selected": red,
      "--color-tag-neutral": surface0,
      "--color-tag-neutral-text": subtext1,
      "--color-tag-normal": blue,
      "--color-tag-normal-text": base,
      "--color-tag-positive-hover": green,
      "--color-tag-positive-normal": green,
      "--color-tag-positive-normal-text": base,
      "--color-tag-positive-pressing": green,
      "--color-tag-positive-selected": green,
      "--color-tag-pressing": surface1,
      "--color-tag-selected": surface1,
      "--color-text-brand": mauve,
      "--color-text-discreet": subtext1,
      "--color-text-discreet-inv": subtext1,
      "--color-text-error": red,
      "--color-text-info": sky,
      "--color-text-main": text,
      "--color-text-main-inv": base,
      "--color-text-marked": sky,
      "--color-text-negative": red,
      "--color-text-positive": green,
      "--color-text-success": green,
      "--color-text-warning": peach,
      "--mint-color-background-backdrop": withAlpha(text, 0.35),
      "--mint-color-background-primary": base,
      "--mint-color-button-buy": blue,
      "--mint-color-button-buy-hover-new": blue,
      "--mint-color-button-primary": mauve,
      "--mint-color-button-primary-hover-new": mauve,
      "--mint-color-button-secondary": surface0,
      "--mint-color-button-secondary-border-new": overlay1,
      "--mint-color-button-secondary-hover-new": surface1,
      "--mint-color-button-sell": red,
      "--mint-color-button-sell-hover-new": red,
      "--mint-color-container-active": mauve,
      "--mint-color-container-brand": surface0,
      "--mint-color-container-destructive": surface0,
      "--mint-color-container-info": surface0,
      "--mint-color-container-inverse": text,
      "--mint-color-container-positive": surface0,
      "--mint-color-container-primary": base,
      "--mint-color-container-primary-hover": surface0,
      "--mint-color-container-private-banking": surface0,
      "--mint-color-container-secondary": crust,
      "--mint-color-container-transparent": withAlpha(base, 0.001),
      "--mint-color-container-warning": surface0,
      "--mint-color-content-brand-decorative": mauve,
      "--mint-color-content-destructive": red,
      "--mint-color-content-inverse": base,
      "--mint-color-content-link": blue,
      "--mint-color-content-link-hover": lavender,
      "--mint-color-content-positive": green,
      "--mint-color-content-primary": text,
      "--mint-color-content-private-banking": text,
      "--mint-color-content-secondary": subtext1,
      "--mint-color-content-warning-decorative": peach,
      "--mint-color-indicator-alert-new": red,
      "--mint-color-morningstar-active": yellow,
      "--mint-color-morningstar-inactive": yellow,
      "--mint-color-persistent-new-white": base,
      "--mint-color-shadow-primary": withAlpha(text, 0.08),
      "--mint-color-sheet-handle": surface0,
      "--mint-color-skeleton-content": surface0,
      "--mint-color-skeleton-highlight": surface1,
      "--mint-color-stroke-active": mauve,
      "--mint-color-stroke-brand": mauve,
      "--mint-color-stroke-destructive": red,
      "--mint-color-stroke-error": red,
      "--mint-color-stroke-high-contrast": overlay1,
      "--mint-color-stroke-info": sky,
      "--mint-color-stroke-positive": green,
      "--mint-color-stroke-primary": surface2,
      "--mint-color-stroke-warning": peach,
      "--mint-color-table-hover": surface0,
      "--mint-color-table-hover-selected": withAlpha(overlay2, 0.3),
      "--mint-color-table-selected": withAlpha(overlay2, 0.25),
      "--mint-color-tag-new-hover": surface1,
      "--mint-color-tag-new-neutral": surface0,
      "--mint-color-tag-new-positive-hover": green,
    },
  };
}
