import type { Theme } from "../../theme/contract";

export type GruvboxPalette = {
  bg0: string;
  bg1: string;
  bg2: string;
  bg3: string;
  bg4: string;
  fg0: string;
  fg1: string;
  fg2: string;
  fg3: string;
  fg4: string;
  gray: string;
  red: string;
  green: string;
  yellow: string;
  blue: string;
  purple: string;
  aqua: string;
  orange: string;
};

const withAlpha = (color: string, alpha: number): string =>
  color.replace("rgb(", "rgba(").replace(")", `, ${alpha})`);

export function compileGruvboxTheme(id: string, name: string, palette: GruvboxPalette): Theme {
  const {
    bg0,
    bg1,
    bg2,
    bg3,
    bg4,
    fg0,
    fg1,
    fg3,
    fg4,
    gray,
    red,
    green,
    yellow,
    blue,
    purple,
    aqua,
    orange,
  } = palette;

  const brand = orange;
  const brandHover = yellow;
  const text = fg1;
  const textDiscreet = fg3;
  const textDisabled = gray;
  const border = bg3;
  const borderSubtle = bg2;
  const borderStrong = bg4;
  const surface = bg1;
  const surfaceHover = bg2;
  const selected = withAlpha(fg4, 0.25);
  const selectedStrong = withAlpha(fg4, 0.3);
  const transparentSurface = withAlpha(bg0, 0.001);

  return {
    id,
    name,
    variables: {
      "--color-border-brand": brand,
      "--color-border-discreet": borderSubtle,
      "--color-border-discreet-a": borderSubtle,
      "--color-border-error": red,
      "--color-border-info": aqua,
      "--color-border-main": borderSubtle,
      "--color-border-subtle": borderSubtle,
      "--color-border-success": green,
      "--color-border-warning": yellow,
      "--color-button-buy-hover": aqua,
      "--color-button-buy-normal": blue,
      "--color-button-buy-normal-text": bg0,
      "--color-button-buy-pressing": blue,
      "--color-button-discreet-border": border,
      "--color-button-discreet-emphasize": brand,
      "--color-button-discreet-hover": surfaceHover,
      "--color-button-discreet-hover-text": text,
      "--color-button-discreet-normal": bg0,
      "--color-button-discreet-normal-text": text,
      "--color-button-discreet-pressing": surfaceHover,
      "--color-button-discreet-pressing-text": text,
      "--color-button-minimal-buy-hover": aqua,
      "--color-button-minimal-buy-hover-text": bg0,
      "--color-button-minimal-buy-normal": "transparent",
      "--color-button-minimal-buy-normal-text": blue,
      "--color-button-minimal-buy-pressing": blue,
      "--color-button-minimal-buy-pressing-text": bg0,
      "--color-button-minimal-discreet-hover-text": text,
      "--color-button-minimal-discreet-normal": "transparent",
      "--color-button-minimal-discreet-normal-text": text,
      "--color-button-minimal-discreet-pressing-text": text,
      "--color-button-minimal-handle": text,
      "--color-button-minimal-primary-hover-text": brandHover,
      "--color-button-minimal-primary-normal": "transparent",
      "--color-button-minimal-primary-normal-text": brand,
      "--color-button-minimal-primary-pressing-text": brand,
      "--color-button-minimal-secondary-hover-text": text,
      "--color-button-minimal-secondary-normal": "transparent",
      "--color-button-minimal-secondary-normal-text": text,
      "--color-button-minimal-secondary-pressing-text": text,
      "--color-button-minimal-sell-hover": red,
      "--color-button-minimal-sell-hover-text": red,
      "--color-button-minimal-sell-normal": "transparent",
      "--color-button-minimal-sell-normal-text": red,
      "--color-button-minimal-sell-pressing": red,
      "--color-button-minimal-sell-pressing-text": red,
      "--color-button-minimal-warning-hover-text": yellow,
      "--color-button-minimal-warning-normal": "transparent",
      "--color-button-minimal-warning-normal-text": yellow,
      "--color-button-minimal-warning-pressing-text": yellow,
      "--color-button-non-essential-normal-text": textDisabled,
      "--color-button-primary-hover": brandHover,
      "--color-button-primary-normal": brand,
      "--color-button-primary-normal-text": bg0,
      "--color-button-primary-pressing": brand,
      "--color-button-secondary-border": border,
      "--color-button-secondary-hover": surfaceHover,
      "--color-button-secondary-hover-text": text,
      "--color-button-secondary-normal": bg0,
      "--color-button-secondary-normal-text": text,
      "--color-button-secondary-pressing": surfaceHover,
      "--color-button-secondary-pressing-text": text,
      "--color-button-sell-hover": red,
      "--color-button-sell-normal": red,
      "--color-button-sell-normal-text": bg0,
      "--color-button-sell-pressing": red,
      "--color-disabled-button-minimal-text": textDisabled,
      "--color-disabled-discreet": surface,
      "--color-disabled-discreet-border": border,
      "--color-disabled-discreet-text": textDisabled,
      "--color-disabled-feedback-icon": textDisabled,
      "--color-disabled-group": surface,
      "--color-disabled-group-border": border,
      "--color-disabled-group-text": textDisabled,
      "--color-disabled-input-checked": textDisabled,
      "--color-disabled-input-placeholder-text": textDisabled,
      "--color-disabled-normal": surface,
      "--color-disabled-normal-border": border,
      "--color-disabled-normal-text": textDisabled,
      "--color-graph-area": withAlpha(brand, 0.2),
      "--color-graph-discreet-stroke": borderSubtle,
      "--color-graph-down": red,
      "--color-graph-gradient-start": withAlpha(brand, 0.2),
      "--color-graph-horizontal-line": yellow,
      "--color-graph-marketmaker-area": surfaceHover,
      "--color-graph-primary-stroke": brand,
      "--color-graph-series-column": surfaceHover,
      "--color-graph-series-column-empty": surfaceHover,
      "--color-graph-series-stroke-a": yellow,
      "--color-graph-series-stroke-b": orange,
      "--color-graph-series-stroke-c": aqua,
      "--color-graph-series-stroke-d": blue,
      "--color-graph-series-stroke-e": purple,
      "--color-graph-series-stroke-f": red,
      "--color-graph-series-stroke-g": green,
      "--color-graph-series-stroke-h": fg3,
      "--color-graph-series-stroke-i": fg4,
      "--color-graph-series-stroke-j": gray,
      "--color-graph-series-stroke-k": borderStrong,
      "--color-graph-surface-info": surface,
      "--color-graph-up": green,
      "--color-icon-discreet": textDiscreet,
      "--color-icon-error": red,
      "--color-icon-feedback-happy": green,
      "--color-icon-feedback-semi-happy": green,
      "--color-icon-feedback-semi-unhappy": red,
      "--color-icon-feedback-unhappy": red,
      "--color-icon-info": aqua,
      "--color-icon-morningstar-rating-emphasize": yellow,
      "--color-icon-morningstar-rating-inactive": yellow,
      "--color-icon-negative": red,
      "--color-icon-neutral": text,
      "--color-icon-non-essential": textDisabled,
      "--color-icon-positive": green,
      "--color-icon-primary": brand,
      "--color-icon-secondary": text,
      "--color-icon-success": green,
      "--color-icon-warning": yellow,
      "--color-indicator-alert": red,
      "--color-indicator-buy": blue,
      "--color-indicator-discreet": text,
      "--color-indicator-incite": green,
      "--color-indicator-info": aqua,
      "--color-indicator-primary": brand,
      "--color-indicator-sell": red,
      "--color-input-border": border,
      "--color-input-border-high-contrast": borderStrong,
      "--color-input-borderless-normal": border,
      "--color-input-borderless-normal-text": border,
      "--color-input-borderless-placeholder-text": textDisabled,
      "--color-input-checked": brand,
      "--color-input-checked-content": bg0,
      "--color-input-emphasize": brand,
      "--color-input-label-text": text,
      "--color-input-normal": bg0,
      "--color-input-normal-text": text,
      "--color-input-placeholder-text": textDiscreet,
      "--color-input-text-field-border-active": brand,
      "--color-input-text-field-border-bottom": borderSubtle,
      "--color-list-neutral-expanded": surface,
      "--color-list-neutral-expanded-a": surface,
      "--color-list-neutral-hover": surfaceHover,
      "--color-list-neutral-pressing": surfaceHover,
      "--color-list-neutral-selected": selected,
      "--color-list-normal": bg0,
      "--color-persistent-black": bg0,
      "--color-persistent-white": fg0,
      "--color-placera-border": borderSubtle,
      "--color-placera-brand": brand,
      "--color-placera-button-hover": surfaceHover,
      "--color-placera-button-minimal-hover-text": text,
      "--color-placera-button-minimal-normal": "transparent",
      "--color-placera-button-minimal-normal-text": text,
      "--color-placera-button-minimal-pressing-text": text,
      "--color-placera-button-normal": brand,
      "--color-placera-button-normal-text": bg0,
      "--color-placera-button-pressing": surfaceHover,
      "--color-placera-surface-hover": surfaceHover,
      "--color-placera-surface-main": bg0,
      "--color-placera-text-brand": brand,
      "--color-placera-text-discreet": textDiscreet,
      "--color-placera-text-main": text,
      "--color-selectable-border": border,
      "--color-selectable-border-high-contrast": borderStrong,
      "--color-selectable-emphasize": brand,
      "--color-selectable-hover": surfaceHover,
      "--color-selectable-hover-text": text,
      "--color-selectable-inactive": brand,
      "--color-selectable-normal": bg0,
      "--color-selectable-normal-text": text,
      "--color-selectable-pressing": surfaceHover,
      "--color-selectable-pressing-text": text,
      "--color-selectable-selected": selected,
      "--color-selectable-selected-text": text,
      "--color-shadow-card": withAlpha(fg0, 0.08),
      "--color-shadow-card-hover": withAlpha(fg0, 0.16),
      "--color-shadow-main": withAlpha(fg0, 0.08),
      "--color-shadow-overlay": withAlpha(fg0, 0.35),
      "--color-skeleton-loading-card": surface,
      "--color-skeleton-loading-element": surface,
      "--color-skeleton-loading-highlight-element": surfaceHover,
      "--color-surface-backdrop": withAlpha(fg0, 0.35),
      "--color-surface-brand": surface,
      "--color-surface-discreet": surface,
      "--color-surface-discreet-a": surface,
      "--color-surface-discreet-hover": surfaceHover,
      "--color-surface-elevated": surface,
      "--color-surface-elevated-primary": surface,
      "--color-surface-elevated-secondary": surface,
      "--color-surface-elevated-tertiary": surface,
      "--color-surface-error": surface,
      "--color-surface-error-a": surface,
      "--color-surface-info": surface,
      "--color-surface-info-a": surface,
      "--color-surface-main": bg0,
      "--color-surface-negative": surface,
      "--color-surface-neutral": surface,
      "--color-surface-neutral-a": surface,
      "--color-surface-offline": bg0,
      "--color-surface-positive": surface,
      "--color-surface-subtle": surface,
      "--color-surface-success": surface,
      "--color-surface-success-a": surface,
      "--color-surface-transparent": transparentSurface,
      "--color-surface-warning": surface,
      "--color-surface-warning-a": surface,
      "--color-tag-hover": surfaceHover,
      "--color-tag-negative-hover": red,
      "--color-tag-negative-normal": red,
      "--color-tag-negative-normal-text": bg0,
      "--color-tag-negative-pressing": red,
      "--color-tag-negative-selected": red,
      "--color-tag-neutral": surface,
      "--color-tag-neutral-text": textDiscreet,
      "--color-tag-normal": blue,
      "--color-tag-normal-text": bg0,
      "--color-tag-positive-hover": green,
      "--color-tag-positive-normal": green,
      "--color-tag-positive-normal-text": bg0,
      "--color-tag-positive-pressing": green,
      "--color-tag-positive-selected": green,
      "--color-tag-pressing": surfaceHover,
      "--color-tag-selected": surfaceHover,
      "--color-text-brand": brand,
      "--color-text-discreet": textDiscreet,
      "--color-text-discreet-inv": textDiscreet,
      "--color-text-error": red,
      "--color-text-info": aqua,
      "--color-text-main": text,
      "--color-text-main-inv": bg0,
      "--color-text-marked": aqua,
      "--color-text-negative": red,
      "--color-text-positive": green,
      "--color-text-success": green,
      "--color-text-warning": yellow,
      "--mint-color-background-backdrop": withAlpha(fg0, 0.35),
      "--mint-color-background-primary": bg0,
      "--mint-color-button-buy": blue,
      "--mint-color-button-buy-hover-new": aqua,
      "--mint-color-button-primary": brand,
      "--mint-color-button-primary-hover-new": brandHover,
      "--mint-color-button-secondary": surface,
      "--mint-color-button-secondary-border-new": border,
      "--mint-color-button-secondary-hover-new": surfaceHover,
      "--mint-color-button-sell": red,
      "--mint-color-button-sell-hover-new": red,
      "--mint-color-container-active": brand,
      "--mint-color-container-brand": surface,
      "--mint-color-container-destructive": surface,
      "--mint-color-container-info": surface,
      "--mint-color-container-inverse": text,
      "--mint-color-container-positive": surface,
      "--mint-color-container-primary": bg0,
      "--mint-color-container-primary-hover": surface,
      "--mint-color-container-private-banking": surface,
      "--mint-color-container-secondary": surface,
      "--mint-color-container-transparent": transparentSurface,
      "--mint-color-container-warning": surface,
      "--mint-color-content-brand-decorative": brand,
      "--mint-color-content-destructive": red,
      "--mint-color-content-inverse": bg0,
      "--mint-color-content-link": blue,
      "--mint-color-content-link-hover": purple,
      "--mint-color-content-positive": green,
      "--mint-color-content-primary": text,
      "--mint-color-content-private-banking": purple,
      "--mint-color-content-secondary": textDiscreet,
      "--mint-color-content-warning-decorative": yellow,
      "--mint-color-indicator-alert-new": red,
      "--mint-color-morningstar-active": yellow,
      "--mint-color-morningstar-inactive": yellow,
      "--mint-color-persistent-new-white": fg0,
      "--mint-color-shadow-primary": withAlpha(fg0, 0.08),
      "--mint-color-sheet-handle": surface,
      "--mint-color-skeleton-content": surface,
      "--mint-color-skeleton-highlight": surfaceHover,
      "--mint-color-stroke-active": brand,
      "--mint-color-stroke-brand": brand,
      "--mint-color-stroke-destructive": red,
      "--mint-color-stroke-error": red,
      "--mint-color-stroke-high-contrast": borderStrong,
      "--mint-color-stroke-info": aqua,
      "--mint-color-stroke-positive": green,
      "--mint-color-stroke-primary": borderSubtle,
      "--mint-color-stroke-warning": yellow,
      "--mint-color-table-hover": surface,
      "--mint-color-table-hover-selected": selectedStrong,
      "--mint-color-table-selected": selected,
      "--mint-color-tag-new-hover": surfaceHover,
      "--mint-color-tag-new-neutral": surface,
      "--mint-color-tag-new-positive-hover": green,
    },
  };
}
