import type { Theme } from "../../theme/contract";

export type RosePinePalette = {
  base: string;
  surface: string;
  overlay: string;
  muted: string;
  subtle: string;
  text: string;
  love: string;
  gold: string;
  rose: string;
  pine: string;
  foam: string;
  iris: string;
  highlightLow: string;
  highlightMed: string;
  highlightHigh: string;
};

const withAlpha = (color: string, alpha: number): string =>
  color.replace("rgb(", "rgba(").replace(")", `, ${alpha})`);

export function compileRosePineTheme(id: string, name: string, palette: RosePinePalette): Theme {
  const {
    base,
    surface,
    overlay,
    muted,
    subtle,
    text,
    love,
    gold,
    rose,
    pine,
    foam,
    iris,
    highlightLow,
    highlightMed,
    highlightHigh,
  } = palette;

  const brand = iris;
  const buy = foam;
  const sell = love;
  const warning = gold;
  const success = pine;
  const info = foam;
  const textDiscreet = subtle;
  const textDisabled = muted;
  const border = highlightHigh;
  const borderSubtle = highlightMed;
  const transparentBackground = withAlpha(base, 0.001);
  const selectedSubtle = highlightMed;
  const selectedStrong = highlightHigh;
  const shadowSubtle = withAlpha(text, 0.08);
  const shadowHover = withAlpha(text, 0.16);
  const shadowOverlay = withAlpha(text, 0.35);
  const backdrop = withAlpha(text, 0.35);

  return {
    id,
    name,
    variables: {
      "--color-border-brand": brand,
      "--color-border-discreet": borderSubtle,
      "--color-border-discreet-a": borderSubtle,
      "--color-border-error": sell,
      "--color-border-info": info,
      "--color-border-main": borderSubtle,
      "--color-border-subtle": borderSubtle,
      "--color-border-success": success,
      "--color-border-warning": warning,
      "--color-button-buy-hover": buy,
      "--color-button-buy-normal": buy,
      "--color-button-buy-normal-text": base,
      "--color-button-buy-pressing": buy,
      "--color-button-discreet-border": border,
      "--color-button-discreet-emphasize": brand,
      "--color-button-discreet-hover": overlay,
      "--color-button-discreet-hover-text": text,
      "--color-button-discreet-normal": base,
      "--color-button-discreet-normal-text": text,
      "--color-button-discreet-pressing": overlay,
      "--color-button-discreet-pressing-text": text,
      "--color-button-minimal-buy-hover": buy,
      "--color-button-minimal-buy-hover-text": buy,
      "--color-button-minimal-buy-normal": "transparent",
      "--color-button-minimal-buy-normal-text": buy,
      "--color-button-minimal-buy-pressing": buy,
      "--color-button-minimal-buy-pressing-text": buy,
      "--color-button-minimal-discreet-hover-text": text,
      "--color-button-minimal-discreet-normal": "transparent",
      "--color-button-minimal-discreet-normal-text": text,
      "--color-button-minimal-discreet-pressing-text": text,
      "--color-button-minimal-handle": text,
      "--color-button-minimal-primary-hover-text": brand,
      "--color-button-minimal-primary-normal": "transparent",
      "--color-button-minimal-primary-normal-text": brand,
      "--color-button-minimal-primary-pressing-text": brand,
      "--color-button-minimal-secondary-hover-text": text,
      "--color-button-minimal-secondary-normal": "transparent",
      "--color-button-minimal-secondary-normal-text": text,
      "--color-button-minimal-secondary-pressing-text": text,
      "--color-button-minimal-sell-hover": sell,
      "--color-button-minimal-sell-hover-text": sell,
      "--color-button-minimal-sell-normal": "transparent",
      "--color-button-minimal-sell-normal-text": sell,
      "--color-button-minimal-sell-pressing": sell,
      "--color-button-minimal-sell-pressing-text": sell,
      "--color-button-minimal-warning-hover-text": warning,
      "--color-button-minimal-warning-normal": "transparent",
      "--color-button-minimal-warning-normal-text": warning,
      "--color-button-minimal-warning-pressing-text": warning,
      "--color-button-non-essential-normal-text": textDisabled,
      "--color-button-primary-hover": brand,
      "--color-button-primary-normal": brand,
      "--color-button-primary-normal-text": base,
      "--color-button-primary-pressing": brand,
      "--color-button-secondary-border": border,
      "--color-button-secondary-hover": overlay,
      "--color-button-secondary-hover-text": text,
      "--color-button-secondary-normal": surface,
      "--color-button-secondary-normal-text": text,
      "--color-button-secondary-pressing": overlay,
      "--color-button-secondary-pressing-text": text,
      "--color-button-sell-hover": sell,
      "--color-button-sell-normal": sell,
      "--color-button-sell-normal-text": base,
      "--color-button-sell-pressing": sell,
      "--color-disabled-button-minimal-text": textDisabled,
      "--color-disabled-discreet": surface,
      "--color-disabled-discreet-border": borderSubtle,
      "--color-disabled-discreet-text": textDisabled,
      "--color-disabled-feedback-icon": textDisabled,
      "--color-disabled-group": surface,
      "--color-disabled-group-border": borderSubtle,
      "--color-disabled-group-text": textDisabled,
      "--color-disabled-input-checked": textDisabled,
      "--color-disabled-input-placeholder-text": textDisabled,
      "--color-disabled-normal": surface,
      "--color-disabled-normal-border": borderSubtle,
      "--color-disabled-normal-text": textDisabled,
      "--color-graph-area": withAlpha(brand, 0.2),
      "--color-graph-discreet-stroke": borderSubtle,
      "--color-graph-down": sell,
      "--color-graph-gradient-start": withAlpha(brand, 0.2),
      "--color-graph-horizontal-line": warning,
      "--color-graph-marketmaker-area": overlay,
      "--color-graph-primary-stroke": brand,
      "--color-graph-series-column": overlay,
      "--color-graph-series-column-empty": overlay,
      "--color-graph-series-stroke-a": rose,
      "--color-graph-series-stroke-b": brand,
      "--color-graph-series-stroke-c": warning,
      "--color-graph-series-stroke-d": info,
      "--color-graph-series-stroke-e": success,
      "--color-graph-series-stroke-f": sell,
      "--color-graph-series-stroke-g": textDiscreet,
      "--color-graph-series-stroke-h": textDisabled,
      "--color-graph-series-stroke-i": text,
      "--color-graph-series-stroke-j": overlay,
      "--color-graph-series-stroke-k": border,
      "--color-graph-surface-info": surface,
      "--color-graph-up": success,
      "--color-icon-discreet": textDiscreet,
      "--color-icon-error": sell,
      "--color-icon-feedback-happy": success,
      "--color-icon-feedback-semi-happy": success,
      "--color-icon-feedback-semi-unhappy": sell,
      "--color-icon-feedback-unhappy": sell,
      "--color-icon-info": info,
      "--color-icon-morningstar-rating-emphasize": warning,
      "--color-icon-morningstar-rating-inactive": warning,
      "--color-icon-negative": sell,
      "--color-icon-neutral": text,
      "--color-icon-non-essential": textDisabled,
      "--color-icon-positive": success,
      "--color-icon-primary": brand,
      "--color-icon-secondary": text,
      "--color-icon-success": success,
      "--color-icon-warning": warning,
      "--color-indicator-alert": sell,
      "--color-indicator-buy": buy,
      "--color-indicator-discreet": textDiscreet,
      "--color-indicator-incite": success,
      "--color-indicator-info": info,
      "--color-indicator-primary": brand,
      "--color-indicator-sell": sell,
      "--color-input-border": border,
      "--color-input-border-high-contrast": border,
      "--color-input-borderless-normal": border,
      "--color-input-borderless-normal-text": textDiscreet,
      "--color-input-borderless-placeholder-text": textDisabled,
      "--color-input-checked": brand,
      "--color-input-checked-content": base,
      "--color-input-emphasize": brand,
      "--color-input-label-text": text,
      "--color-input-normal": surface,
      "--color-input-normal-text": text,
      "--color-input-placeholder-text": textDiscreet,
      "--color-input-text-field-border-active": brand,
      "--color-input-text-field-border-bottom": borderSubtle,
      "--color-list-neutral-expanded": surface,
      "--color-list-neutral-expanded-a": surface,
      "--color-list-neutral-hover": overlay,
      "--color-list-neutral-pressing": overlay,
      "--color-list-neutral-selected": selectedSubtle,
      "--color-list-normal": base,
      "--color-persistent-black": base,
      "--color-persistent-white": text,
      "--color-placera-border": borderSubtle,
      "--color-placera-brand": brand,
      "--color-placera-button-hover": overlay,
      "--color-placera-button-minimal-hover-text": text,
      "--color-placera-button-minimal-normal": "transparent",
      "--color-placera-button-minimal-normal-text": text,
      "--color-placera-button-minimal-pressing-text": text,
      "--color-placera-button-normal": brand,
      "--color-placera-button-normal-text": base,
      "--color-placera-button-pressing": overlay,
      "--color-placera-surface-hover": overlay,
      "--color-placera-surface-main": base,
      "--color-placera-text-brand": brand,
      "--color-placera-text-discreet": textDiscreet,
      "--color-placera-text-main": text,
      "--color-selectable-border": border,
      "--color-selectable-border-high-contrast": border,
      "--color-selectable-emphasize": brand,
      "--color-selectable-hover": overlay,
      "--color-selectable-hover-text": text,
      "--color-selectable-inactive": brand,
      "--color-selectable-normal": base,
      "--color-selectable-normal-text": text,
      "--color-selectable-pressing": overlay,
      "--color-selectable-pressing-text": text,
      "--color-selectable-selected": selectedSubtle,
      "--color-selectable-selected-text": text,
      "--color-shadow-card": shadowSubtle,
      "--color-shadow-card-hover": shadowHover,
      "--color-shadow-main": shadowSubtle,
      "--color-shadow-overlay": shadowOverlay,
      "--color-skeleton-loading-card": surface,
      "--color-skeleton-loading-element": surface,
      "--color-skeleton-loading-highlight-element": overlay,
      "--color-surface-backdrop": backdrop,
      "--color-surface-brand": surface,
      "--color-surface-discreet": surface,
      "--color-surface-discreet-a": surface,
      "--color-surface-discreet-hover": overlay,
      "--color-surface-elevated": surface,
      "--color-surface-elevated-primary": surface,
      "--color-surface-elevated-secondary": surface,
      "--color-surface-elevated-tertiary": surface,
      "--color-surface-error": surface,
      "--color-surface-error-a": surface,
      "--color-surface-info": surface,
      "--color-surface-info-a": surface,
      "--color-surface-main": base,
      "--color-surface-negative": surface,
      "--color-surface-neutral": surface,
      "--color-surface-neutral-a": surface,
      "--color-surface-offline": base,
      "--color-surface-positive": surface,
      "--color-surface-subtle": highlightLow,
      "--color-surface-success": surface,
      "--color-surface-success-a": surface,
      "--color-surface-transparent": transparentBackground,
      "--color-surface-warning": surface,
      "--color-surface-warning-a": surface,
      "--color-tag-hover": overlay,
      "--color-tag-negative-hover": sell,
      "--color-tag-negative-normal": sell,
      "--color-tag-negative-normal-text": base,
      "--color-tag-negative-pressing": sell,
      "--color-tag-negative-selected": sell,
      "--color-tag-neutral": surface,
      "--color-tag-neutral-text": textDiscreet,
      "--color-tag-normal": buy,
      "--color-tag-normal-text": base,
      "--color-tag-positive-hover": success,
      "--color-tag-positive-normal": success,
      "--color-tag-positive-normal-text": base,
      "--color-tag-positive-pressing": success,
      "--color-tag-positive-selected": success,
      "--color-tag-pressing": overlay,
      "--color-tag-selected": overlay,
      "--color-text-brand": brand,
      "--color-text-discreet": textDiscreet,
      "--color-text-discreet-inv": textDiscreet,
      "--color-text-error": sell,
      "--color-text-info": info,
      "--color-text-main": text,
      "--color-text-main-inv": base,
      "--color-text-marked": info,
      "--color-text-negative": sell,
      "--color-text-positive": success,
      "--color-text-success": success,
      "--color-text-warning": warning,
      "--mint-color-background-backdrop": backdrop,
      "--mint-color-background-primary": base,
      "--mint-color-button-buy": buy,
      "--mint-color-button-buy-hover-new": buy,
      "--mint-color-button-primary": brand,
      "--mint-color-button-primary-hover-new": brand,
      "--mint-color-button-secondary": surface,
      "--mint-color-button-secondary-border-new": border,
      "--mint-color-button-secondary-hover-new": overlay,
      "--mint-color-button-sell": sell,
      "--mint-color-button-sell-hover-new": sell,
      "--mint-color-container-active": brand,
      "--mint-color-container-brand": surface,
      "--mint-color-container-destructive": surface,
      "--mint-color-container-info": surface,
      "--mint-color-container-inverse": text,
      "--mint-color-container-positive": surface,
      "--mint-color-container-primary": base,
      "--mint-color-container-primary-hover": surface,
      "--mint-color-container-private-banking": surface,
      "--mint-color-container-secondary": highlightLow,
      "--mint-color-container-transparent": transparentBackground,
      "--mint-color-container-warning": surface,
      "--mint-color-content-brand-decorative": brand,
      "--mint-color-content-destructive": sell,
      "--mint-color-content-inverse": base,
      "--mint-color-content-link": brand,
      "--mint-color-content-link-hover": rose,
      "--mint-color-content-positive": success,
      "--mint-color-content-primary": text,
      "--mint-color-content-private-banking": brand,
      "--mint-color-content-secondary": textDiscreet,
      "--mint-color-content-warning-decorative": warning,
      "--mint-color-indicator-alert-new": sell,
      "--mint-color-morningstar-active": warning,
      "--mint-color-morningstar-inactive": warning,
      "--mint-color-persistent-new-white": text,
      "--mint-color-shadow-primary": shadowSubtle,
      "--mint-color-sheet-handle": surface,
      "--mint-color-skeleton-content": surface,
      "--mint-color-skeleton-highlight": overlay,
      "--mint-color-stroke-active": brand,
      "--mint-color-stroke-brand": brand,
      "--mint-color-stroke-destructive": sell,
      "--mint-color-stroke-error": sell,
      "--mint-color-stroke-high-contrast": border,
      "--mint-color-stroke-info": info,
      "--mint-color-stroke-positive": success,
      "--mint-color-stroke-primary": borderSubtle,
      "--mint-color-stroke-warning": warning,
      "--mint-color-table-hover": surface,
      "--mint-color-table-hover-selected": selectedStrong,
      "--mint-color-table-selected": selectedSubtle,
      "--mint-color-tag-new-hover": overlay,
      "--mint-color-tag-new-neutral": surface,
      "--mint-color-tag-new-positive-hover": success,
    },
  };
}
