import type { Theme } from "../theme/contract";

const nord0 = "rgb(46, 52, 64)";
const nord1 = "rgb(59, 66, 82)";
const nord2 = "rgb(67, 76, 94)";
const nord3 = "rgb(76, 86, 106)";
const nord4 = "rgb(216, 222, 233)";
const nord5 = "rgb(229, 233, 240)";
const nord6 = "rgb(236, 239, 244)";
const nord7 = "rgb(143, 188, 187)";
const nord8 = "rgb(136, 192, 208)";
const nord9 = "rgb(129, 161, 193)";
const nord10 = "rgb(94, 129, 172)";
const nord11 = "rgb(191, 97, 106)";
const nord12 = "rgb(208, 135, 112)";
const nord13 = "rgb(235, 203, 139)";
const nord14 = "rgb(163, 190, 140)";
const nord15 = "rgb(180, 142, 173)";

const withAlpha = (color: string, alpha: number): string =>
  color.replace("rgb(", "rgba(").replace(")", `, ${alpha})`);

const background = nord0;
const elevated = nord1;
const elevatedHover = nord2;
const border = nord3;
const text = nord6;
const textDiscreet = nord4;
const textDisabled = nord3;
const primary = nord8;
const primaryHover = nord7;
const secondary = nord9;
const secondaryStrong = nord10;
const error = nord11;
const warning = nord13;
const success = nord14;
const uncommon = nord15;
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const advanced = nord12;
const selected = nord2;
const transparentBackground = withAlpha(background, 0.001);

const nordTheme: Theme = {
  id: "nord",
  name: "Nord",
  variables: {
    "--color-border-brand": primary,
    "--color-border-discreet": border,
    "--color-border-discreet-a": border,
    "--color-border-error": error,
    "--color-border-info": primary,
    "--color-border-main": border,
    "--color-border-subtle": elevatedHover,
    "--color-border-success": success,
    "--color-border-warning": warning,
    "--color-button-buy-hover": secondary,
    "--color-button-buy-normal": secondary,
    "--color-button-buy-normal-text": background,
    "--color-button-buy-pressing": secondaryStrong,
    "--color-button-discreet-border": border,
    "--color-button-discreet-emphasize": primary,
    "--color-button-discreet-hover": elevatedHover,
    "--color-button-discreet-hover-text": text,
    "--color-button-discreet-normal": background,
    "--color-button-discreet-normal-text": text,
    "--color-button-discreet-pressing": elevatedHover,
    "--color-button-discreet-pressing-text": text,
    "--color-button-minimal-buy-hover": secondary,
    "--color-button-minimal-buy-hover-text": background,
    "--color-button-minimal-buy-normal": "transparent",
    "--color-button-minimal-buy-normal-text": secondary,
    "--color-button-minimal-buy-pressing": secondaryStrong,
    "--color-button-minimal-buy-pressing-text": background,
    "--color-button-minimal-discreet-hover-text": text,
    "--color-button-minimal-discreet-normal": "transparent",
    "--color-button-minimal-discreet-normal-text": text,
    "--color-button-minimal-discreet-pressing-text": text,
    "--color-button-minimal-handle": text,
    "--color-button-minimal-primary-hover-text": primaryHover,
    "--color-button-minimal-primary-normal": "transparent",
    "--color-button-minimal-primary-normal-text": primary,
    "--color-button-minimal-primary-pressing-text": primary,
    "--color-button-minimal-secondary-hover-text": text,
    "--color-button-minimal-secondary-normal": "transparent",
    "--color-button-minimal-secondary-normal-text": text,
    "--color-button-minimal-secondary-pressing-text": text,
    "--color-button-minimal-sell-hover": error,
    "--color-button-minimal-sell-hover-text": text,
    "--color-button-minimal-sell-normal": "transparent",
    "--color-button-minimal-sell-normal-text": error,
    "--color-button-minimal-sell-pressing": error,
    "--color-button-minimal-sell-pressing-text": text,
    "--color-button-minimal-warning-hover-text": warning,
    "--color-button-minimal-warning-normal": "transparent",
    "--color-button-minimal-warning-normal-text": warning,
    "--color-button-minimal-warning-pressing-text": warning,
    "--color-button-non-essential-normal-text": textDisabled,
    "--color-button-primary-hover": primaryHover,
    "--color-button-primary-normal": primary,
    "--color-button-primary-normal-text": background,
    "--color-button-primary-pressing": secondary,
    "--color-button-secondary-border": border,
    "--color-button-secondary-hover": elevatedHover,
    "--color-button-secondary-hover-text": text,
    "--color-button-secondary-normal": elevated,
    "--color-button-secondary-normal-text": text,
    "--color-button-secondary-pressing": elevatedHover,
    "--color-button-secondary-pressing-text": text,
    "--color-button-sell-hover": error,
    "--color-button-sell-normal": error,
    "--color-button-sell-normal-text": text,
    "--color-button-sell-pressing": error,
    "--color-disabled-button-minimal-text": textDisabled,
    "--color-disabled-discreet": elevated,
    "--color-disabled-discreet-border": border,
    "--color-disabled-discreet-text": textDisabled,
    "--color-disabled-feedback-icon": textDisabled,
    "--color-disabled-group": elevated,
    "--color-disabled-group-border": border,
    "--color-disabled-group-text": textDisabled,
    "--color-disabled-input-checked": textDisabled,
    "--color-disabled-input-placeholder-text": textDisabled,
    "--color-disabled-normal": elevated,
    "--color-disabled-normal-border": border,
    "--color-disabled-normal-text": textDisabled,
    "--color-graph-area": withAlpha(primary, 0.2),
    "--color-graph-discreet-stroke": border,
    "--color-graph-down": error,
    "--color-graph-gradient-start": withAlpha(primary, 0.2),
    "--color-graph-horizontal-line": warning,
    "--color-graph-marketmaker-area": elevatedHover,
    "--color-graph-primary-stroke": primary,
    "--color-graph-series-column": elevatedHover,
    "--color-graph-series-column-empty": elevatedHover,
    "--color-graph-series-stroke-a": nord7,
    "--color-graph-series-stroke-b": nord8,
    "--color-graph-series-stroke-c": nord9,
    "--color-graph-series-stroke-d": nord10,
    "--color-graph-series-stroke-e": nord15,
    "--color-graph-series-stroke-f": nord11,
    "--color-graph-series-stroke-g": nord12,
    "--color-graph-series-stroke-h": nord13,
    "--color-graph-series-stroke-i": nord14,
    "--color-graph-series-stroke-j": nord5,
    "--color-graph-series-stroke-k": nord6,
    "--color-graph-surface-info": elevated,
    "--color-graph-up": success,
    "--color-icon-discreet": textDiscreet,
    "--color-icon-error": error,
    "--color-icon-feedback-happy": success,
    "--color-icon-feedback-semi-happy": success,
    "--color-icon-feedback-semi-unhappy": error,
    "--color-icon-feedback-unhappy": error,
    "--color-icon-info": primary,
    "--color-icon-morningstar-rating-emphasize": warning,
    "--color-icon-morningstar-rating-inactive": warning,
    "--color-icon-negative": error,
    "--color-icon-neutral": text,
    "--color-icon-non-essential": textDisabled,
    "--color-icon-positive": success,
    "--color-icon-primary": primary,
    "--color-icon-secondary": text,
    "--color-icon-success": success,
    "--color-icon-warning": warning,
    "--color-indicator-alert": error,
    "--color-indicator-buy": secondary,
    "--color-indicator-discreet": textDiscreet,
    "--color-indicator-incite": success,
    "--color-indicator-info": primary,
    "--color-indicator-primary": primary,
    "--color-indicator-sell": error,
    "--color-input-border": border,
    "--color-input-border-high-contrast": textDiscreet,
    "--color-input-borderless-normal": border,
    "--color-input-borderless-normal-text": textDiscreet,
    "--color-input-borderless-placeholder-text": textDisabled,
    "--color-input-checked": primary,
    "--color-input-checked-content": background,
    "--color-input-emphasize": primary,
    "--color-input-label-text": text,
    "--color-input-normal": background,
    "--color-input-normal-text": text,
    "--color-input-placeholder-text": textDiscreet,
    "--color-input-text-field-border-active": primary,
    "--color-input-text-field-border-bottom": border,
    "--color-list-neutral-expanded": elevated,
    "--color-list-neutral-expanded-a": elevated,
    "--color-list-neutral-hover": elevatedHover,
    "--color-list-neutral-pressing": elevatedHover,
    "--color-list-neutral-selected": selected,
    "--color-list-normal": background,
    "--color-persistent-black": background,
    "--color-persistent-white": text,
    "--color-placera-border": border,
    "--color-placera-brand": primary,
    "--color-placera-button-hover": elevatedHover,
    "--color-placera-button-minimal-hover-text": text,
    "--color-placera-button-minimal-normal": "transparent",
    "--color-placera-button-minimal-normal-text": text,
    "--color-placera-button-minimal-pressing-text": text,
    "--color-placera-button-normal": primary,
    "--color-placera-button-normal-text": background,
    "--color-placera-button-pressing": elevatedHover,
    "--color-placera-surface-hover": elevatedHover,
    "--color-placera-surface-main": background,
    "--color-placera-text-brand": primary,
    "--color-placera-text-discreet": textDiscreet,
    "--color-placera-text-main": text,
    "--color-selectable-border": border,
    "--color-selectable-border-high-contrast": textDiscreet,
    "--color-selectable-emphasize": primary,
    "--color-selectable-hover": elevatedHover,
    "--color-selectable-hover-text": text,
    "--color-selectable-inactive": primary,
    "--color-selectable-normal": background,
    "--color-selectable-normal-text": text,
    "--color-selectable-pressing": elevatedHover,
    "--color-selectable-pressing-text": text,
    "--color-selectable-selected": selected,
    "--color-selectable-selected-text": text,
    "--color-shadow-card": withAlpha(background, 0.35),
    "--color-shadow-card-hover": withAlpha(background, 0.45),
    "--color-shadow-main": withAlpha(background, 0.35),
    "--color-shadow-overlay": withAlpha(background, 0.65),
    "--color-skeleton-loading-card": elevated,
    "--color-skeleton-loading-element": elevated,
    "--color-skeleton-loading-highlight-element": elevatedHover,
    "--color-surface-backdrop": withAlpha(background, 0.65),
    "--color-surface-brand": elevated,
    "--color-surface-discreet": elevated,
    "--color-surface-discreet-a": elevated,
    "--color-surface-discreet-hover": elevatedHover,
    "--color-surface-elevated": elevated,
    "--color-surface-elevated-primary": elevated,
    "--color-surface-elevated-secondary": elevated,
    "--color-surface-elevated-tertiary": elevated,
    "--color-surface-error": elevated,
    "--color-surface-error-a": elevated,
    "--color-surface-info": elevated,
    "--color-surface-info-a": elevated,
    "--color-surface-main": background,
    "--color-surface-negative": elevated,
    "--color-surface-neutral": elevated,
    "--color-surface-neutral-a": elevated,
    "--color-surface-offline": background,
    "--color-surface-positive": elevated,
    "--color-surface-subtle": background,
    "--color-surface-success": elevated,
    "--color-surface-success-a": elevated,
    "--color-surface-transparent": transparentBackground,
    "--color-surface-warning": elevated,
    "--color-surface-warning-a": elevated,
    "--color-tag-hover": elevatedHover,
    "--color-tag-negative-hover": error,
    "--color-tag-negative-normal": error,
    "--color-tag-negative-normal-text": text,
    "--color-tag-negative-pressing": error,
    "--color-tag-negative-selected": error,
    "--color-tag-neutral": elevated,
    "--color-tag-neutral-text": textDiscreet,
    "--color-tag-normal": primary,
    "--color-tag-normal-text": background,
    "--color-tag-positive-hover": success,
    "--color-tag-positive-normal": success,
    "--color-tag-positive-normal-text": background,
    "--color-tag-positive-pressing": success,
    "--color-tag-positive-selected": success,
    "--color-tag-pressing": elevatedHover,
    "--color-tag-selected": elevatedHover,
    "--color-text-brand": primary,
    "--color-text-discreet": textDiscreet,
    "--color-text-discreet-inv": textDiscreet,
    "--color-text-error": error,
    "--color-text-info": primary,
    "--color-text-main": text,
    "--color-text-main-inv": background,
    "--color-text-marked": primary,
    "--color-text-negative": error,
    "--color-text-positive": success,
    "--color-text-success": success,
    "--color-text-warning": warning,
    "--mint-color-background-backdrop": withAlpha(background, 0.65),
    "--mint-color-background-primary": background,
    "--mint-color-button-buy": secondary,
    "--mint-color-button-buy-hover-new": secondaryStrong,
    "--mint-color-button-primary": primary,
    "--mint-color-button-primary-hover-new": primaryHover,
    "--mint-color-button-secondary": elevated,
    "--mint-color-button-secondary-border-new": border,
    "--mint-color-button-secondary-hover-new": elevatedHover,
    "--mint-color-button-sell": error,
    "--mint-color-button-sell-hover-new": error,
    "--mint-color-container-active": primary,
    "--mint-color-container-brand": elevated,
    "--mint-color-container-destructive": elevated,
    "--mint-color-container-info": elevated,
    "--mint-color-container-inverse": text,
    "--mint-color-container-positive": elevated,
    "--mint-color-container-primary": background,
    "--mint-color-container-primary-hover": elevated,
    "--mint-color-container-private-banking": elevated,
    "--mint-color-container-secondary": background,
    "--mint-color-container-transparent": transparentBackground,
    "--mint-color-container-warning": elevated,
    "--mint-color-content-brand-decorative": primary,
    "--mint-color-content-destructive": error,
    "--mint-color-content-inverse": background,
    "--mint-color-content-link": primary,
    "--mint-color-content-link-hover": primaryHover,
    "--mint-color-content-positive": success,
    "--mint-color-content-primary": text,
    "--mint-color-content-private-banking": uncommon,
    "--mint-color-content-secondary": textDiscreet,
    "--mint-color-content-warning-decorative": warning,
    "--mint-color-indicator-alert-new": error,
    "--mint-color-morningstar-active": warning,
    "--mint-color-morningstar-inactive": warning,
    "--mint-color-persistent-new-white": text,
    "--mint-color-shadow-primary": withAlpha(background, 0.35),
    "--mint-color-sheet-handle": elevated,
    "--mint-color-skeleton-content": elevated,
    "--mint-color-skeleton-highlight": elevatedHover,
    "--mint-color-stroke-active": primary,
    "--mint-color-stroke-brand": primary,
    "--mint-color-stroke-destructive": error,
    "--mint-color-stroke-error": error,
    "--mint-color-stroke-high-contrast": textDiscreet,
    "--mint-color-stroke-info": primary,
    "--mint-color-stroke-positive": success,
    "--mint-color-stroke-primary": border,
    "--mint-color-stroke-warning": warning,
    "--mint-color-table-hover": elevated,
    "--mint-color-table-hover-selected": selected,
    "--mint-color-table-selected": selected,
    "--mint-color-tag-new-hover": elevatedHover,
    "--mint-color-tag-new-neutral": elevated,
    "--mint-color-tag-new-positive-hover": success,
  },
};

export default nordTheme;
