import type { Theme } from "../theme/contract";

const background = "rgb(17, 28, 24)";
const backgroundSubtle = "rgb(17, 34, 28)";
const backgroundLowest = "rgb(7, 40, 32)";
const elevated = backgroundSubtle;
const elevatedHover = "rgb(35, 55, 43)";
const border = "rgb(33, 66, 55)";
const borderSubtle = elevatedHover;
const selected = "rgb(54, 69, 56)";
const shadow = "rgb(0, 0, 0)";
const text = "rgb(247, 232, 178)";
const textDiscreet = "rgb(193, 196, 151)";
const textDisabled = "rgb(50, 71, 59)";
const onAccent = background;
const primary = "rgb(71, 206, 173)";
const primaryHover = "rgb(158, 235, 179)";
const buy = "rgb(84, 158, 106)";
const buyHover = "rgb(99, 176, 122)";
const sell = "rgb(255, 83, 69)";
const warning = "rgb(229, 199, 54)";
const success = buy;
const info = "rgb(45, 213, 183)";
const privateBanking = "rgb(210, 104, 156)";
const graphA = "rgb(222, 178, 102)";
const graphB = primary;
const graphC = warning;
const graphD = info;
const graphE = "rgb(117, 187, 179)";
const graphF = privateBanking;
const graphG = sell;
const graphH = success;
const graphI = "rgb(80, 148, 117)";
const graphJ = textDiscreet;
const graphK = text;

const withAlpha = (color: string, alpha: number): string =>
  color.replace("rgb(", "rgba(").replace(")", `, ${alpha})`);

const transparentBackground = withAlpha(background, 0.001);
const selectedSubtle = withAlpha(selected, 0.25);
const selectedStrong = withAlpha(selected, 0.3);
const shadowSubtle = withAlpha(shadow, 0.18);
const shadowHover = withAlpha(shadow, 0.28);
const shadowOverlay = withAlpha(shadow, 0.55);
const backdrop = withAlpha(shadow, 0.65);

const osakaJadeTheme: Theme = {
  id: "osaka-jade",
  name: "Osaka Jade",
  variables: {
    "--color-border-brand": primary,
    "--color-border-discreet": border,
    "--color-border-discreet-a": border,
    "--color-border-error": sell,
    "--color-border-info": info,
    "--color-border-main": border,
    "--color-border-subtle": borderSubtle,
    "--color-border-success": success,
    "--color-border-warning": warning,
    "--color-button-buy-hover": buyHover,
    "--color-button-buy-normal": buy,
    "--color-button-buy-normal-text": onAccent,
    "--color-button-buy-pressing": buyHover,
    "--color-button-discreet-border": border,
    "--color-button-discreet-emphasize": primary,
    "--color-button-discreet-hover": elevatedHover,
    "--color-button-discreet-hover-text": text,
    "--color-button-discreet-normal": background,
    "--color-button-discreet-normal-text": text,
    "--color-button-discreet-pressing": elevatedHover,
    "--color-button-discreet-pressing-text": text,
    "--color-button-minimal-buy-hover": buyHover,
    "--color-button-minimal-buy-hover-text": buyHover,
    "--color-button-minimal-buy-normal": "transparent",
    "--color-button-minimal-buy-normal-text": buy,
    "--color-button-minimal-buy-pressing": buyHover,
    "--color-button-minimal-buy-pressing-text": buyHover,
    "--color-button-minimal-discreet-hover-text": text,
    "--color-button-minimal-discreet-normal": "transparent",
    "--color-button-minimal-discreet-normal-text": text,
    "--color-button-minimal-discreet-pressing-text": text,
    "--color-button-minimal-handle": text,
    "--color-button-minimal-primary-hover-text": primaryHover,
    "--color-button-minimal-primary-normal": "transparent",
    "--color-button-minimal-primary-normal-text": primary,
    "--color-button-minimal-primary-pressing-text": primaryHover,
    "--color-button-minimal-secondary-hover-text": text,
    "--color-button-minimal-secondary-normal": "transparent",
    "--color-button-minimal-secondary-normal-text": text,
    "--color-button-minimal-secondary-pressing-text": text,
    "--color-button-minimal-sell-hover": sell,
    "--color-button-minimal-sell-hover-text": sell,
    "--color-button-minimal-sell-normal": "transparent",
    "--color-button-minimal-sell-normal-text": sell,
    "--color-button-minimal-sell-pressing": sell,
    "--color-button-minimal-sell-pressing-text": sell,
    "--color-button-minimal-warning-hover-text": warning,
    "--color-button-minimal-warning-normal": "transparent",
    "--color-button-minimal-warning-normal-text": warning,
    "--color-button-minimal-warning-pressing-text": warning,
    "--color-button-non-essential-normal-text": textDisabled,
    "--color-button-primary-hover": primaryHover,
    "--color-button-primary-normal": primary,
    "--color-button-primary-normal-text": onAccent,
    "--color-button-primary-pressing": primaryHover,
    "--color-button-secondary-border": border,
    "--color-button-secondary-hover": elevatedHover,
    "--color-button-secondary-hover-text": text,
    "--color-button-secondary-normal": elevated,
    "--color-button-secondary-normal-text": text,
    "--color-button-secondary-pressing": elevatedHover,
    "--color-button-secondary-pressing-text": text,
    "--color-button-sell-hover": sell,
    "--color-button-sell-normal": sell,
    "--color-button-sell-normal-text": onAccent,
    "--color-button-sell-pressing": sell,
    "--color-disabled-button-minimal-text": textDisabled,
    "--color-disabled-discreet": elevated,
    "--color-disabled-discreet-border": borderSubtle,
    "--color-disabled-discreet-text": textDisabled,
    "--color-disabled-feedback-icon": textDisabled,
    "--color-disabled-group": elevated,
    "--color-disabled-group-border": borderSubtle,
    "--color-disabled-group-text": textDisabled,
    "--color-disabled-input-checked": textDisabled,
    "--color-disabled-input-placeholder-text": textDisabled,
    "--color-disabled-normal": elevated,
    "--color-disabled-normal-border": borderSubtle,
    "--color-disabled-normal-text": textDisabled,
    "--color-graph-area": withAlpha(primary, 0.2),
    "--color-graph-discreet-stroke": borderSubtle,
    "--color-graph-down": sell,
    "--color-graph-gradient-start": withAlpha(primary, 0.2),
    "--color-graph-horizontal-line": warning,
    "--color-graph-marketmaker-area": elevatedHover,
    "--color-graph-primary-stroke": primary,
    "--color-graph-series-column": borderSubtle,
    "--color-graph-series-column-empty": borderSubtle,
    "--color-graph-series-stroke-a": graphA,
    "--color-graph-series-stroke-b": graphB,
    "--color-graph-series-stroke-c": graphC,
    "--color-graph-series-stroke-d": graphD,
    "--color-graph-series-stroke-e": graphE,
    "--color-graph-series-stroke-f": graphF,
    "--color-graph-series-stroke-g": graphG,
    "--color-graph-series-stroke-h": graphH,
    "--color-graph-series-stroke-i": graphI,
    "--color-graph-series-stroke-j": graphJ,
    "--color-graph-series-stroke-k": graphK,
    "--color-graph-surface-info": elevated,
    "--color-graph-up": success,
    "--color-icon-discreet": textDiscreet,
    "--color-icon-error": sell,
    "--color-icon-feedback-happy": success,
    "--color-icon-feedback-semi-happy": success,
    "--color-icon-feedback-semi-unhappy": sell,
    "--color-icon-feedback-unhappy": sell,
    "--color-icon-info": info,
    "--color-icon-morningstar-rating-emphasize": warning,
    "--color-icon-morningstar-rating-inactive": warning,
    "--color-icon-negative": sell,
    "--color-icon-neutral": text,
    "--color-icon-non-essential": textDisabled,
    "--color-icon-positive": success,
    "--color-icon-primary": primary,
    "--color-icon-secondary": text,
    "--color-icon-success": success,
    "--color-icon-warning": warning,
    "--color-indicator-alert": sell,
    "--color-indicator-buy": buy,
    "--color-indicator-discreet": textDiscreet,
    "--color-indicator-incite": success,
    "--color-indicator-info": info,
    "--color-indicator-primary": primary,
    "--color-indicator-sell": sell,
    "--color-input-border": border,
    "--color-input-border-high-contrast": textDiscreet,
    "--color-input-borderless-normal": border,
    "--color-input-borderless-normal-text": textDiscreet,
    "--color-input-borderless-placeholder-text": textDisabled,
    "--color-input-checked": primary,
    "--color-input-checked-content": onAccent,
    "--color-input-emphasize": primary,
    "--color-input-label-text": text,
    "--color-input-normal": background,
    "--color-input-normal-text": text,
    "--color-input-placeholder-text": textDiscreet,
    "--color-input-text-field-border-active": primary,
    "--color-input-text-field-border-bottom": borderSubtle,
    "--color-list-neutral-expanded": elevated,
    "--color-list-neutral-expanded-a": elevated,
    "--color-list-neutral-hover": elevatedHover,
    "--color-list-neutral-pressing": elevatedHover,
    "--color-list-neutral-selected": selectedSubtle,
    "--color-list-normal": background,
    "--color-persistent-black": backgroundLowest,
    "--color-persistent-white": text,
    "--color-placera-border": borderSubtle,
    "--color-placera-brand": primary,
    "--color-placera-button-hover": elevatedHover,
    "--color-placera-button-minimal-hover-text": text,
    "--color-placera-button-minimal-normal": "transparent",
    "--color-placera-button-minimal-normal-text": text,
    "--color-placera-button-minimal-pressing-text": text,
    "--color-placera-button-normal": primary,
    "--color-placera-button-normal-text": onAccent,
    "--color-placera-button-pressing": elevatedHover,
    "--color-placera-surface-hover": elevatedHover,
    "--color-placera-surface-main": background,
    "--color-placera-text-brand": primary,
    "--color-placera-text-discreet": textDiscreet,
    "--color-placera-text-main": text,
    "--color-selectable-border": border,
    "--color-selectable-border-high-contrast": textDiscreet,
    "--color-selectable-emphasize": primary,
    "--color-selectable-hover": elevatedHover,
    "--color-selectable-hover-text": text,
    "--color-selectable-inactive": primary,
    "--color-selectable-normal": background,
    "--color-selectable-normal-text": text,
    "--color-selectable-pressing": elevatedHover,
    "--color-selectable-pressing-text": text,
    "--color-selectable-selected": selectedSubtle,
    "--color-selectable-selected-text": text,
    "--color-shadow-card": shadowSubtle,
    "--color-shadow-card-hover": shadowHover,
    "--color-shadow-main": shadowSubtle,
    "--color-shadow-overlay": shadowOverlay,
    "--color-skeleton-loading-card": elevated,
    "--color-skeleton-loading-element": elevated,
    "--color-skeleton-loading-highlight-element": elevatedHover,
    "--color-surface-backdrop": backdrop,
    "--color-surface-brand": elevated,
    "--color-surface-discreet": elevated,
    "--color-surface-discreet-a": elevated,
    "--color-surface-discreet-hover": elevatedHover,
    "--color-surface-elevated": elevated,
    "--color-surface-elevated-primary": elevated,
    "--color-surface-elevated-secondary": elevated,
    "--color-surface-elevated-tertiary": elevated,
    "--color-surface-error": elevated,
    "--color-surface-error-a": elevated,
    "--color-surface-info": elevated,
    "--color-surface-info-a": elevated,
    "--color-surface-main": background,
    "--color-surface-negative": elevated,
    "--color-surface-neutral": elevated,
    "--color-surface-neutral-a": elevated,
    "--color-surface-offline": backgroundLowest,
    "--color-surface-positive": elevated,
    "--color-surface-subtle": backgroundSubtle,
    "--color-surface-success": elevated,
    "--color-surface-success-a": elevated,
    "--color-surface-transparent": transparentBackground,
    "--color-surface-warning": elevated,
    "--color-surface-warning-a": elevated,
    "--color-tag-hover": elevatedHover,
    "--color-tag-negative-hover": sell,
    "--color-tag-negative-normal": sell,
    "--color-tag-negative-normal-text": onAccent,
    "--color-tag-negative-pressing": sell,
    "--color-tag-negative-selected": sell,
    "--color-tag-neutral": elevated,
    "--color-tag-neutral-text": textDiscreet,
    "--color-tag-normal": buy,
    "--color-tag-normal-text": onAccent,
    "--color-tag-positive-hover": success,
    "--color-tag-positive-normal": success,
    "--color-tag-positive-normal-text": onAccent,
    "--color-tag-positive-pressing": success,
    "--color-tag-positive-selected": success,
    "--color-tag-pressing": elevatedHover,
    "--color-tag-selected": elevatedHover,
    "--color-text-brand": primary,
    "--color-text-discreet": textDiscreet,
    "--color-text-discreet-inv": textDiscreet,
    "--color-text-error": sell,
    "--color-text-info": info,
    "--color-text-main": text,
    "--color-text-main-inv": onAccent,
    "--color-text-marked": info,
    "--color-text-negative": sell,
    "--color-text-positive": success,
    "--color-text-success": success,
    "--color-text-warning": warning,
    "--mint-color-background-backdrop": backdrop,
    "--mint-color-background-primary": background,
    "--mint-color-button-buy": buy,
    "--mint-color-button-buy-hover-new": buyHover,
    "--mint-color-button-primary": primary,
    "--mint-color-button-primary-hover-new": primaryHover,
    "--mint-color-button-secondary": elevated,
    "--mint-color-button-secondary-border-new": border,
    "--mint-color-button-secondary-hover-new": elevatedHover,
    "--mint-color-button-sell": sell,
    "--mint-color-button-sell-hover-new": sell,
    "--mint-color-container-active": primary,
    "--mint-color-container-brand": elevated,
    "--mint-color-container-destructive": elevated,
    "--mint-color-container-info": elevated,
    "--mint-color-container-inverse": text,
    "--mint-color-container-positive": elevated,
    "--mint-color-container-primary": background,
    "--mint-color-container-primary-hover": elevated,
    "--mint-color-container-private-banking": elevated,
    "--mint-color-container-secondary": backgroundLowest,
    "--mint-color-container-transparent": transparentBackground,
    "--mint-color-container-warning": elevated,
    "--mint-color-content-brand-decorative": primary,
    "--mint-color-content-destructive": sell,
    "--mint-color-content-inverse": onAccent,
    "--mint-color-content-link": buy,
    "--mint-color-content-link-hover": primaryHover,
    "--mint-color-content-positive": success,
    "--mint-color-content-primary": text,
    "--mint-color-content-private-banking": privateBanking,
    "--mint-color-content-secondary": textDiscreet,
    "--mint-color-content-warning-decorative": warning,
    "--mint-color-indicator-alert-new": sell,
    "--mint-color-morningstar-active": warning,
    "--mint-color-morningstar-inactive": warning,
    "--mint-color-persistent-new-white": text,
    "--mint-color-shadow-primary": shadowSubtle,
    "--mint-color-sheet-handle": elevated,
    "--mint-color-skeleton-content": elevated,
    "--mint-color-skeleton-highlight": elevatedHover,
    "--mint-color-stroke-active": primary,
    "--mint-color-stroke-brand": primary,
    "--mint-color-stroke-destructive": sell,
    "--mint-color-stroke-error": sell,
    "--mint-color-stroke-high-contrast": textDiscreet,
    "--mint-color-stroke-info": info,
    "--mint-color-stroke-positive": success,
    "--mint-color-stroke-primary": borderSubtle,
    "--mint-color-stroke-warning": warning,
    "--mint-color-table-hover": elevated,
    "--mint-color-table-hover-selected": selectedStrong,
    "--mint-color-table-selected": selectedSubtle,
    "--mint-color-tag-new-hover": elevatedHover,
    "--mint-color-tag-new-neutral": elevated,
    "--mint-color-tag-new-positive-hover": success,
  },
};

export default osakaJadeTheme;
