import type { Theme } from "../theme/contract";

const navy = "rgb(0, 23, 46)";
const navyElevated = "rgb(1, 32, 78)";
const tealElevated = "rgb(10, 58, 69)";
const tealBorder = "rgb(19, 78, 90)";
const tealMuted = "rgb(95, 143, 150)";
const seafoamText = "rgb(167, 201, 198)";
const sand = "rgb(255, 241, 218)";
const cream = "rgb(246, 220, 172)";
const redOrange = "rgb(248, 85, 37)";
const amber = "rgb(250, 169, 104)";
const orange = "rgb(233, 123, 60)";
const teal = "rgb(2, 131, 145)";
const seafoam = "rgb(140, 191, 184)";
const aqua = "rgb(63, 143, 138)";
const deepTeal = "rgb(23, 107, 115)";
const transparentBackground = "rgba(0, 23, 46, 0.001)";
const selectedSubtle = "rgba(19, 78, 90, 0.25)";
const selectedStrong = "rgba(19, 78, 90, 0.3)";
const shadowSubtle = "rgba(0, 0, 0, 0.18)";
const shadowHover = "rgba(0, 0, 0, 0.28)";
const shadowOverlay = "rgba(0, 0, 0, 0.55)";
const backdrop = "rgba(0, 0, 0, 0.65)";
const primaryArea = "rgba(250, 169, 104, 0.2)";

const retro82Theme: Theme = {
  id: "retro-82",
  name: "Retro 82",
  variables: {
    "--color-border-brand": amber,
    "--color-border-discreet": tealBorder,
    "--color-border-discreet-a": tealBorder,
    "--color-border-error": redOrange,
    "--color-border-info": seafoam,
    "--color-border-main": tealBorder,
    "--color-border-subtle": tealElevated,
    "--color-border-success": teal,
    "--color-border-warning": orange,
    "--color-button-buy-hover": seafoam,
    "--color-button-buy-normal": teal,
    "--color-button-buy-normal-text": navy,
    "--color-button-buy-pressing": seafoam,
    "--color-button-discreet-border": tealBorder,
    "--color-button-discreet-emphasize": amber,
    "--color-button-discreet-hover": tealElevated,
    "--color-button-discreet-hover-text": cream,
    "--color-button-discreet-normal": navy,
    "--color-button-discreet-normal-text": cream,
    "--color-button-discreet-pressing": tealElevated,
    "--color-button-discreet-pressing-text": cream,
    "--color-button-minimal-buy-hover": seafoam,
    "--color-button-minimal-buy-hover-text": seafoam,
    "--color-button-minimal-buy-normal": "transparent",
    "--color-button-minimal-buy-normal-text": teal,
    "--color-button-minimal-buy-pressing": seafoam,
    "--color-button-minimal-buy-pressing-text": seafoam,
    "--color-button-minimal-discreet-hover-text": cream,
    "--color-button-minimal-discreet-normal": "transparent",
    "--color-button-minimal-discreet-normal-text": cream,
    "--color-button-minimal-discreet-pressing-text": cream,
    "--color-button-minimal-handle": cream,
    "--color-button-minimal-primary-hover-text": sand,
    "--color-button-minimal-primary-normal": "transparent",
    "--color-button-minimal-primary-normal-text": amber,
    "--color-button-minimal-primary-pressing-text": sand,
    "--color-button-minimal-secondary-hover-text": cream,
    "--color-button-minimal-secondary-normal": "transparent",
    "--color-button-minimal-secondary-normal-text": cream,
    "--color-button-minimal-secondary-pressing-text": cream,
    "--color-button-minimal-sell-hover": redOrange,
    "--color-button-minimal-sell-hover-text": redOrange,
    "--color-button-minimal-sell-normal": "transparent",
    "--color-button-minimal-sell-normal-text": redOrange,
    "--color-button-minimal-sell-pressing": redOrange,
    "--color-button-minimal-sell-pressing-text": redOrange,
    "--color-button-minimal-warning-hover-text": orange,
    "--color-button-minimal-warning-normal": "transparent",
    "--color-button-minimal-warning-normal-text": orange,
    "--color-button-minimal-warning-pressing-text": orange,
    "--color-button-non-essential-normal-text": tealMuted,
    "--color-button-primary-hover": sand,
    "--color-button-primary-normal": amber,
    "--color-button-primary-normal-text": navy,
    "--color-button-primary-pressing": sand,
    "--color-button-secondary-border": tealBorder,
    "--color-button-secondary-hover": tealElevated,
    "--color-button-secondary-hover-text": cream,
    "--color-button-secondary-normal": navyElevated,
    "--color-button-secondary-normal-text": cream,
    "--color-button-secondary-pressing": tealElevated,
    "--color-button-secondary-pressing-text": cream,
    "--color-button-sell-hover": redOrange,
    "--color-button-sell-normal": redOrange,
    "--color-button-sell-normal-text": navy,
    "--color-button-sell-pressing": redOrange,
    "--color-disabled-button-minimal-text": tealMuted,
    "--color-disabled-discreet": navyElevated,
    "--color-disabled-discreet-border": tealElevated,
    "--color-disabled-discreet-text": tealMuted,
    "--color-disabled-feedback-icon": tealMuted,
    "--color-disabled-group": navyElevated,
    "--color-disabled-group-border": tealElevated,
    "--color-disabled-group-text": tealMuted,
    "--color-disabled-input-checked": tealMuted,
    "--color-disabled-input-placeholder-text": tealMuted,
    "--color-disabled-normal": navyElevated,
    "--color-disabled-normal-border": tealElevated,
    "--color-disabled-normal-text": tealMuted,
    "--color-graph-area": primaryArea,
    "--color-graph-discreet-stroke": tealElevated,
    "--color-graph-down": redOrange,
    "--color-graph-gradient-start": primaryArea,
    "--color-graph-horizontal-line": orange,
    "--color-graph-marketmaker-area": tealElevated,
    "--color-graph-primary-stroke": amber,
    "--color-graph-series-column": tealElevated,
    "--color-graph-series-column-empty": tealElevated,
    "--color-graph-series-stroke-a": amber,
    "--color-graph-series-stroke-b": teal,
    "--color-graph-series-stroke-c": orange,
    "--color-graph-series-stroke-d": seafoam,
    "--color-graph-series-stroke-e": aqua,
    "--color-graph-series-stroke-f": redOrange,
    "--color-graph-series-stroke-g": deepTeal,
    "--color-graph-series-stroke-h": sand,
    "--color-graph-series-stroke-i": seafoamText,
    "--color-graph-series-stroke-j": tealMuted,
    "--color-graph-series-stroke-k": tealBorder,
    "--color-graph-surface-info": navyElevated,
    "--color-graph-up": teal,
    "--color-icon-discreet": seafoamText,
    "--color-icon-error": redOrange,
    "--color-icon-feedback-happy": teal,
    "--color-icon-feedback-semi-happy": teal,
    "--color-icon-feedback-semi-unhappy": redOrange,
    "--color-icon-feedback-unhappy": redOrange,
    "--color-icon-info": seafoam,
    "--color-icon-morningstar-rating-emphasize": orange,
    "--color-icon-morningstar-rating-inactive": orange,
    "--color-icon-negative": redOrange,
    "--color-icon-neutral": cream,
    "--color-icon-non-essential": tealMuted,
    "--color-icon-positive": teal,
    "--color-icon-primary": amber,
    "--color-icon-secondary": cream,
    "--color-icon-success": teal,
    "--color-icon-warning": orange,
    "--color-indicator-alert": redOrange,
    "--color-indicator-buy": teal,
    "--color-indicator-discreet": seafoamText,
    "--color-indicator-incite": teal,
    "--color-indicator-info": seafoam,
    "--color-indicator-primary": amber,
    "--color-indicator-sell": redOrange,
    "--color-input-border": tealBorder,
    "--color-input-border-high-contrast": seafoamText,
    "--color-input-borderless-normal": tealBorder,
    "--color-input-borderless-normal-text": seafoamText,
    "--color-input-borderless-placeholder-text": tealMuted,
    "--color-input-checked": amber,
    "--color-input-checked-content": navy,
    "--color-input-emphasize": amber,
    "--color-input-label-text": cream,
    "--color-input-normal": navy,
    "--color-input-normal-text": cream,
    "--color-input-placeholder-text": seafoamText,
    "--color-input-text-field-border-active": amber,
    "--color-input-text-field-border-bottom": tealElevated,
    "--color-list-neutral-expanded": navyElevated,
    "--color-list-neutral-expanded-a": navyElevated,
    "--color-list-neutral-hover": tealElevated,
    "--color-list-neutral-pressing": tealElevated,
    "--color-list-neutral-selected": selectedSubtle,
    "--color-list-normal": navy,
    "--color-persistent-black": navy,
    "--color-persistent-white": cream,
    "--color-placera-border": tealElevated,
    "--color-placera-brand": amber,
    "--color-placera-button-hover": tealElevated,
    "--color-placera-button-minimal-hover-text": cream,
    "--color-placera-button-minimal-normal": "transparent",
    "--color-placera-button-minimal-normal-text": cream,
    "--color-placera-button-minimal-pressing-text": cream,
    "--color-placera-button-normal": amber,
    "--color-placera-button-normal-text": navy,
    "--color-placera-button-pressing": tealElevated,
    "--color-placera-surface-hover": tealElevated,
    "--color-placera-surface-main": navy,
    "--color-placera-text-brand": amber,
    "--color-placera-text-discreet": seafoamText,
    "--color-placera-text-main": cream,
    "--color-selectable-border": tealBorder,
    "--color-selectable-border-high-contrast": seafoamText,
    "--color-selectable-emphasize": amber,
    "--color-selectable-hover": tealElevated,
    "--color-selectable-hover-text": cream,
    "--color-selectable-inactive": amber,
    "--color-selectable-normal": navy,
    "--color-selectable-normal-text": cream,
    "--color-selectable-pressing": tealElevated,
    "--color-selectable-pressing-text": cream,
    "--color-selectable-selected": selectedSubtle,
    "--color-selectable-selected-text": cream,
    "--color-shadow-card": shadowSubtle,
    "--color-shadow-card-hover": shadowHover,
    "--color-shadow-main": shadowSubtle,
    "--color-shadow-overlay": shadowOverlay,
    "--color-skeleton-loading-card": navyElevated,
    "--color-skeleton-loading-element": navyElevated,
    "--color-skeleton-loading-highlight-element": tealElevated,
    "--color-surface-backdrop": backdrop,
    "--color-surface-brand": navyElevated,
    "--color-surface-discreet": navyElevated,
    "--color-surface-discreet-a": navyElevated,
    "--color-surface-discreet-hover": tealElevated,
    "--color-surface-elevated": navyElevated,
    "--color-surface-elevated-primary": navyElevated,
    "--color-surface-elevated-secondary": navyElevated,
    "--color-surface-elevated-tertiary": navyElevated,
    "--color-surface-error": navyElevated,
    "--color-surface-error-a": navyElevated,
    "--color-surface-info": navyElevated,
    "--color-surface-info-a": navyElevated,
    "--color-surface-main": navy,
    "--color-surface-negative": navyElevated,
    "--color-surface-neutral": navyElevated,
    "--color-surface-neutral-a": navyElevated,
    "--color-surface-offline": navy,
    "--color-surface-positive": navyElevated,
    "--color-surface-subtle": navyElevated,
    "--color-surface-success": navyElevated,
    "--color-surface-success-a": navyElevated,
    "--color-surface-transparent": transparentBackground,
    "--color-surface-warning": navyElevated,
    "--color-surface-warning-a": navyElevated,
    "--color-tag-hover": tealElevated,
    "--color-tag-negative-hover": redOrange,
    "--color-tag-negative-normal": redOrange,
    "--color-tag-negative-normal-text": navy,
    "--color-tag-negative-pressing": redOrange,
    "--color-tag-negative-selected": redOrange,
    "--color-tag-neutral": navyElevated,
    "--color-tag-neutral-text": seafoamText,
    "--color-tag-normal": teal,
    "--color-tag-normal-text": navy,
    "--color-tag-positive-hover": teal,
    "--color-tag-positive-normal": teal,
    "--color-tag-positive-normal-text": navy,
    "--color-tag-positive-pressing": teal,
    "--color-tag-positive-selected": teal,
    "--color-tag-pressing": tealElevated,
    "--color-tag-selected": tealElevated,
    "--color-text-brand": amber,
    "--color-text-discreet": seafoamText,
    "--color-text-discreet-inv": seafoamText,
    "--color-text-error": redOrange,
    "--color-text-info": seafoam,
    "--color-text-main": cream,
    "--color-text-main-inv": navy,
    "--color-text-marked": seafoam,
    "--color-text-negative": redOrange,
    "--color-text-positive": teal,
    "--color-text-success": teal,
    "--color-text-warning": orange,
    "--mint-color-background-backdrop": backdrop,
    "--mint-color-background-primary": navy,
    "--mint-color-button-buy": teal,
    "--mint-color-button-buy-hover-new": seafoam,
    "--mint-color-button-primary": amber,
    "--mint-color-button-primary-hover-new": sand,
    "--mint-color-button-secondary": navyElevated,
    "--mint-color-button-secondary-border-new": tealBorder,
    "--mint-color-button-secondary-hover-new": tealElevated,
    "--mint-color-button-sell": redOrange,
    "--mint-color-button-sell-hover-new": redOrange,
    "--mint-color-container-active": amber,
    "--mint-color-container-brand": navyElevated,
    "--mint-color-container-destructive": navyElevated,
    "--mint-color-container-info": navyElevated,
    "--mint-color-container-inverse": cream,
    "--mint-color-container-positive": navyElevated,
    "--mint-color-container-primary": navy,
    "--mint-color-container-primary-hover": navyElevated,
    "--mint-color-container-private-banking": navyElevated,
    "--mint-color-container-secondary": navy,
    "--mint-color-container-transparent": transparentBackground,
    "--mint-color-container-warning": navyElevated,
    "--mint-color-content-brand-decorative": amber,
    "--mint-color-content-destructive": redOrange,
    "--mint-color-content-inverse": navy,
    "--mint-color-content-link": teal,
    "--mint-color-content-link-hover": sand,
    "--mint-color-content-positive": teal,
    "--mint-color-content-primary": cream,
    "--mint-color-content-private-banking": aqua,
    "--mint-color-content-secondary": seafoamText,
    "--mint-color-content-warning-decorative": orange,
    "--mint-color-indicator-alert-new": redOrange,
    "--mint-color-morningstar-active": orange,
    "--mint-color-morningstar-inactive": orange,
    "--mint-color-persistent-new-white": cream,
    "--mint-color-shadow-primary": shadowSubtle,
    "--mint-color-sheet-handle": navyElevated,
    "--mint-color-skeleton-content": navyElevated,
    "--mint-color-skeleton-highlight": tealElevated,
    "--mint-color-stroke-active": amber,
    "--mint-color-stroke-brand": amber,
    "--mint-color-stroke-destructive": redOrange,
    "--mint-color-stroke-error": redOrange,
    "--mint-color-stroke-high-contrast": seafoamText,
    "--mint-color-stroke-info": seafoam,
    "--mint-color-stroke-positive": teal,
    "--mint-color-stroke-primary": tealElevated,
    "--mint-color-stroke-warning": orange,
    "--mint-color-table-hover": navyElevated,
    "--mint-color-table-hover-selected": selectedStrong,
    "--mint-color-table-selected": selectedSubtle,
    "--mint-color-tag-new-hover": tealElevated,
    "--mint-color-tag-new-neutral": navyElevated,
    "--mint-color-tag-new-positive-hover": teal,
  },
};

export default retro82Theme;
